### ISSUE TITLE
XMRig Config

### ISSUE THREAD

**Issue by StarLordRammi** [xmrig/xmrig-amd#125]
please update
https://config.xmrig.com/
 for 2.7.0
i use batch files and old files are not compatible anymore since i use double thread and custom intensity

thank you so much

**Comment by weltall666** [comment]
I'm having the same problem with awesome miner. Altough I can use "-c config.json" via xmrig-amd.exe or start.cmd, I can't start it with awesome miner, it rejects config.json and closes it. When I replace with 2.6.1 exe file, it starts properly. I'm trying to use memory_chunck and strided_index, since I get more hashrate with this.

**Comment by StarLordRammi** [comment]
`xmrig-amd.exe --donate-level 1 --opencl-platform 1 --opencl-devices 0,1 --opencl-launch 1000x8,1000x8,1024x8,1024x8 -o stellite.ingest.cryptoknight.cc:16222 -u walletaddress.15000 -p Rig --variant xtl -k`

this works with older version but doesnt work anymore on newest one

**Comment by BobbyGR** [comment]
Same here

**Comment by xmrig** [comment]
Fixed in v2.7.2-beta.
