### ISSUE TITLE
Nicehash incorrect & rejected share

### ISSUE THREAD

**Issue by SinggihMAC** [xmrig/xmrig-amd#129]
Please fix the miner for nicehash compability, there's some rejected and incorrect share while mining on nicehash both in cn v7 or cn-heavy.
Some of them is : "invalid nounce, is your miner compatible with nicehash?"
The config used for nicehash cn v7 is algo : cryptonight, variant : 1, nicehash : true.
And for nicehash cn-heavy is algo : cn-heavy, variant : 0, nicehash : true.
Thanks

**Comment by xmrig** [comment]
It rare bug, it might be hardware problem or something like that, nicehash is supported, but for some users it not work well for some reason, please provide all possible information it may help fugue it out.
Thank you.

**Comment by SinggihMAC** [comment]
It's something like this :
https://github.com/fireice-uk/xmr-stak/issues/835
It was well fine on cryptonight, but some rejected on nicehash v7 nor heavy. But it's only happens on nicehash, and running well on direct coin mining (xmr, xhv, etc)

**Comment by jrodrigog** [comment]
It is not a rare bug... It is a well known problem with _nicehash_:

https://github.com/fireice-uk/xmr-stak/issues/835
https://github.com/fireice-uk/xmr-stak/issues/309

For example right now I have:

```
46 Job not found.
18 Invalid nonce; is miner not compatible with NiceHash?
1900 total results.

``` 
And:
```
61 Job not found.
15 Invalid nonce; is miner not compatible with NiceHash?
2032 total results.
```
As a side note a `--fastjobswitch` option implemented as the **first variant** (i) that @psychocrypt  explained on this comment https://github.com/fireice-uk/xmr-stak/issues/835#issuecomment-363541422 is totally required for _nicehash_ because it will scrap some good hashing time that right now is totally lost.

But maybe, as @psychocrypt noted, this logic on the code will impact _xmr-stak_ performance when using good behaving pools.

**Comment by xmrig** [comment]
Expired shares should not be reason for error `Invalid nonce; is miner not compatible with NiceHash?`. This error should only happen if miner really send invalid nonce, it's simple one byte check.

Please check [nicehash specification](https://github.com/nicehash/Specifications/blob/master/NiceHash_CryptoNight_modification_v1.0.txt). Nicehash choice this byte once per connection, new jobs not change this byte and miner should never change this byte.

If network log available it will be very helpful. If uncomment this line https://github.com/xmrig/xmrig-amd/blob/master/CMakeLists.txt#L179 and rebuild miner, network log will be available in miner console. Same log from xmr-stak will helpful too.
Thank you.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
