### ISSUE TITLE
Cryptonight variant 2 support

### ISSUE THREAD

**Issue by SChernykh** [xmrig/xmrig-amd#159]
@xmrig If you haven't already started working on it for xmrig-amd, I can make a pull request by the end of this week - I have OpenCL code ready, just need to port it to xmrig codebase.

**Comment by xmrig** [comment]
Thank you, would be nice, CPU/network part of AMD miner is already updated to variant 2 support (dev branch), so just need update OpenCL part.

**Comment by xmrminer01102018** [comment]
I have xmrig-amd with variant 1 running with Windows level hash rate under Linux.  Since variant 2 is under dev branch, I just downloaded and did the test run and it went back to low hash rate only.  Your insight would be helpful.  The following is the tested matrix for Linux so far for Vega 56; add about 70 H/s more for Vega 64 and FE.

                                             Running with amd-gpupro 18.10            Running with amd-gpupro 18.30
v1 with 18.10 compile.               1100 H/s                                                 1980 H/s                        
v1 with 18.30 compile                Not Tested                                            0 H/s
v2 with 18.10 compile                1200 H/s                                                0 H/s
v2 with 18.30 compile               Not Tested                                             0 H/s

Note: The power usage is holding around 110 W for non-zero hash rate. About 80 W for zero hash rate.
