### ISSUE TITLE
mining stopped after few minutes cnv8 & nicehash

### ISSUE THREAD

**Issue by Quake4** [xmrig/xmrig-amd#176]
![image](https://user-images.githubusercontent.com/29517243/47221332-c196d480-d3bc-11e8-95c0-c6292ea4a3ae.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/47221403-e2f7c080-d3bc-11e8-8ccc-86d084ce1384.png)

**Comment by Quake4** [comment]
git submodule add http://gitlab.dev.ckrt.ru/ckrt/platform/module/database.git
![image](https://user-images.githubusercontent.com/29517243/47222394-4aaf0b00-d3bf-11e8-9d36-31f9c7eb9948.png)

**Comment by Quake4** [comment]
RX560 2Gb version

**Comment by NmxMilk** [comment]
Check your event viewer for abnormal events. 
If you see:
 Event ID:      4101
Description:
Display driver amdkmdap stopped responding and has successfully recovered.
then this is the cause of the hashrate drop.

I have been getting the same with my Rx 550. And the only solution was to reduce the instensity to 256 instead of 432 sacrifying a percentage of my hashrate !

**Comment by Quake4** [comment]
I use autoconfigure, and dont ser params for card manually.

**Comment by BoWozZ** [comment]
Fix your Problem

https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Adrenalin-Edition-18.5.1-Release-Notes.aspx

**Comment by Quake4** [comment]
my drivers version is 18.5.1

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
