### ISSUE TITLE
error cl_build_program_failure when calling clbuildprogram when open official release xmrig-amd-2.11.1

### ISSUE THREAD

**Issue by badsos** [xmrig/xmrig-amd#219]
hi
I got error when open AMD version of official release xmrig-amd-2.11.1
I have windows 10 with AMD-Catalyst-15.7.1-Win10-64bit installed.

[http://prntscr.com/mjj79m](url) this is the pic for my problem when open for the fist time (all default values)
as it shows I tryed to use it on AMD Radeon HD 6450 card.

I have changed intensity and worksize, but it won't work.

**Comment by Altaiar** [comment]
i have same problem too amd Radeon HD 6850 tested with this version 2.12.0

**Comment by Altaiar** [comment]
more info
![1](https://user-images.githubusercontent.com/12981994/53354794-d3751f00-393c-11e9-8f66-8ea8d0d91344.PNG)

**Comment by Antokolos** [comment]
The same error on Ubuntu for Radeon HD 6670:
```
[2019-03-02 14:00:06]  * ABOUT        XMRig-AMD/2.13.0 gcc/7.3.0
[2019-03-02 14:00:06]  * LIBS         libuv/1.18.0 OpenCL/2.0 OpenSSL/1.1.0g microhttpd/0.9.59
[2019-03-02 14:00:06]  * CPU           x64 -AES
[2019-03-02 14:00:06]  * ALGO         cryptonight, donate=1%
[2019-03-02 14:00:06]  * POOL #1      pool.minexmr.com:5555 variant auto
[2019-03-02 14:00:06]  * COMMANDS     hashrate, pause, resume
[2019-03-02 14:00:06] compiling code and initializing GPUs. This will take a while...
[2019-03-02 14:00:07] #00, GPU #00  (Turks), i:352 (32/256), si:2/2, u:8, cu:6
[2019-03-02 14:00:07]              0.68/1.00/1 GB
[2019-03-02 14:00:07]            CACHE: ./.cache/GN3RWWEF3SBLNCXXDOMWUYSKXRFYS7ZNIL6XDITKYNRMBSGIVRGQ.bin
[2019-03-02 14:00:07] GPU #0 compiling...
[2019-03-02 14:00:07] Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
[2019-03-02 14:00:07] Build log:
[2019-03-02 14:00:07] Failed to start threads.

```

**Comment by xmrig** [comment]
Remove `-cl-fp32-correctly-rounded-divide-sqrt` from this line https://github.com/xmrig/xmrig-amd/blob/master/src/amd/OclCache.cpp#L72, it should fix build issue, but after this change algorithm `cn/gpu` will be broken.
Thank you.

**Comment by MahdiWB** [comment]
> Remove `-cl-fp32-correctly-rounded-divide-sqrt` from this line https://github.com/xmrig/xmrig-amd/blob/master/src/amd/OclCache.cpp#L72, it should fix build issue, but after this change algorithm `cn/gpu` will be broken.
> Thank you.

I have removed `-cl-fp32-correctly-rounded-divide-sqrt` and now xmrig-amd will open and seem to be running but it's not getting any job from the pool! is this because `cn/gpu`  broke or maybe I did something wrong?
Thanks

**Comment by Spudz76** [comment]
> after this change algorithm `cn/gpu` will be broken.
^^^^
^^^^
^^^^

Note correctly-rounded is required for algorithm CN-GPU.  Get newer GPU to run that algo.  Other algos will work.

Old cards pre GCN2 (Hawaii or so) work better with old drivers like 15.x but you still won't get hardware missing features like correctly rounded square roots.  Redwood definitely needs driver **NO NEWER THAN**: [Windows 15.12](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-15-12) or [Linux fglrx 15.201](https://www.amd.com/en/support/graphics/amd-radeon-hd/ati-radeon-hd-5000-series/ati-radeon-hd-5770) but also suspect the Turks from the OP to have the same issue.

AMD completely broke memory handling for all old cards OpenCL functionality after that driver and never intends to fix them.

Double fun part is to run the old driver you have to nuke your Linux and install Ubuntu 14.04 (NON-LTS!!) because no newer distro or kernels will work with the old fglrx.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
