### ISSUE TITLE
ATI/AMD HD 5770 Hash only 100 H/sec

### ISSUE THREAD

**Issue by stark2006** [xmrig/xmrig-amd#22]
I am using ATI/AMD HD 5770 Hash only 100 H/sec with xmrig but with Claymore Cryptonote 9.7 I am getting above 165 h/sec.

I tried to change the intensity from 160 to 256 in xmrig amd, after that I cannot see the Hash count  and in Claymore Cryptonote default hash count is 320.

Now what settings should I use to get maximum work from GPU?

**Comment by cryptonius** [comment]
I have the exact same problem! Dunno if it's OpenCL related (this GPU is VLIW5 arch, not GCN), but I have the latest available AMD drivers (Catalyst 15.7.1) in Windows 10 64-bit.

I'd love to use xmrig-amd instead of Claymore v9.7 (old & unsupported version)... please fix it!

There are lots of people with old hardware out there! I currently use xmrig with Intel Q9550 since you fixed the L2 cache bug and improved the hash rate. :)

**Comment by cryptonius** [comment]
Something that might help:

Claymore v9.7 yields a similar hash rate (~100 H/s) on this GPU if the following option ("-a 3") is not used:

-a	Select algorithm:
	"-a 0" (default) means autoselection.
	"-a 1" fastest mining mode for 290/290x and 270/270x cards.
	"-a 2" low power consumption mode for 290/290x cards. A bit less speed (1%) but less power consumption (10-15%).
	"-a 3" fastest mining for old cards (6xxx and 5xxx). 
	"-a 4" fastest mining for recent cards (280x, 270/270x etc). 
	You can also specify mode for every card separately, for example, "-a 1234".
	It is very important for good mining speed to select correct "-a" and "-h" values for your cards.
	For old cards 5xxx and 6xxx use "-a 3" mode only, otherwise you can get "LowDifficultyShare" errors from pool.

Perhaps you need to add a similar optimization option for VLIW5/VLIW4 arch GPUs...

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
