### ISSUE TITLE
Trojan found - according to windows defender

### ISSUE THREAD

**Issue by vmajor** [xmrig/xmrig-amd#23]
Windows defender reports a trojan in v2.4.3-beta2

**Comment by alexcom** [comment]
A lot of AV software recognize miners as viruses. Sometimes because they are packed binaries( if closed source) and sometimes just because many companies use their software installers to install a miner that will hog your CPU power for their benefit. It's a right thing for AV software to report about miners. Their classification of miners as Trojans is not correct of course but there's nothing we can do about it. Download sources, review them and build miner yourself if you in doubt about binaries.

**Comment by semtex41** [comment]
Trojan:Win32/Tiggre!plock is what it is showing. That isnt the same as saying the AV is detecting it as a PUP/Hackertool. 

It might be best to have one of the devs submit it officially:
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by alexcom** [comment]
@semtex41 You know that virus classification is a thing each AV vendor invents by themselves. They just *decided* to call it a trojan at MS. I've built a binary myself and submitted for scan to VirusTotal. Here's a result: [link](https://www.virustotal.com/#/file/2bfb2140d7606648d13b222888e323f1af12c423cc2cc05c2686f320c81741aa/detection).
If the link is still valid you'll see that only 14 of 61 AV programs detected it as virus. Most famous AV programs(Kaspersky, ESET) detected it correctly as miner. You'll never please each AV software engine and you never control the decision behind classification. There's no sense in wasting time trying to make AV vendor to update software just to identify xmrig correctly as miner or tool. Worth mention that MS Defender is a crappy AV software and MS itself states that Defender is not a replacement for real AV software. Therefore there's no sense in attempts to satisfy it.
