### ISSUE TITLE
XMRig AMD crashes with no error message

### ISSUE THREAD

**Issue by SlavisaBakic** [xmrig/xmrig-amd#263]
XMRig AMD v2.14.4
Windows 10 Enterprise LTSC 2019 x64 (17763.615)
AMD driver v19.7.1

Celeron G3900, 5 x Radeon R9 390

XMRig AMD stops without any error message. Driver problem or something else?

Log file

```
 * ABOUT        XMRig-AMD/2.14.4 MSVC/2017
 * LIBS         libuv/1.29.1 OpenCL/2.0 OpenSSL/1.1.1b microhttpd/0.9.63
 * CPU          Intel(R) Celeron(R) CPU G3900 @ 2.80GHz x64 AES
 * ALGO         cryptonight, donate=5%
 * POOL #1      pool.minexmr.com:7777 variant auto
 * COMMANDS     hashrate, pause, resume
[2019-07-11 13:16:43] compiling code and initializing GPUs. This will take a while...
[2019-07-11 13:16:43] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
[2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
[2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
[2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
[2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
[2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
[2019-07-11 13:16:43] #00, GPU #00 AMD Radeon (TM) R9 390 Series (Hawaii), i:960 (8/256), si:2/2, u:8, cu:40
[2019-07-11 13:16:43]              1.88/3.95/8 GB
[2019-07-11 13:16:43] GPU #0 compiling...
```

**Comment by Yairimedinac4621** [comment]
.#-*- mining pool online 020319 id 1d03000 #_: 
 : #_ /

**Comment by Yairimedinac4621** [comment]
Tienes una invitación para el siguiente evento.

Título: Re: [xmrig/xmrig-amd] XMRig AMD crashes with no error message (#263)

.#-*- mining pool online 020319 id 1d03000 #_:
-*- : #_ / ["Ërror ! Ëvent i"] _

   ["https://avatars3.githubusercontent.com/u/31129590?s=180&v=4 ._
https://github.com/SlavisaBakic  
@ ://github.com/xmrig/xmrig-amd/issues/263?email_source=notifications&email_token=AK5XGQGTGIESAFGR4YEW42LP64NFBA5CNFSM4IBCFEIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G6TPZSA","https://yandex.com/images/touch/search?cbir_id=1595214%2F4jfhYOm2-jGoex1WJP_iUQ&cbird=3&rpt=imageview&redircnt=1562848583.2"]`'._#
   _ / #_
'`
Obtener Outlook para Android



De: SlavisaBakic
Enviado: jueves, 11 de julio 4:51
Asunto: [xmrig/xmrig-amd] XMRig AMD crashes with no error message (#263)
Para: xmrig/xmrig-amd
Cc: Subscribed


XMRig AMD v2.14.4
Windows 10 Enterprise LTSC 2019 x64 (17763.615)
AMD driver v19.7.1
Celeron G3900, 5 x Radeon R9 390
XMRig AMD stops without any error message. Driver problem or something else?
Log file
* ABOUT XMRig-AMD/2.14.4 MSVC/2017 * LIBS libuv/1.29.1 OpenCL/2.0  
OpenSSL/1.1.1b microhttpd/0.9.63 * CPU Intel(R) Celeron(R) CPU G3900 @  
2.80GHz x64 AES * ALGO cryptonight, donate=5% * POOL #1  
pool.minexmr.com:7777 variant auto * COMMANDS hashrate, pause, resume  
[2019-07-11 13:16:43] compiling code and initializing GPUs. This will take  
a while... [2019-07-11 13:16:43] found AMD platform index: 0, name:  
Advanced Micro Devices, Inc. [2019-07-11 13:16:43] found OpenCL GPU: AMD  
Radeon (TM) R9 390 Series (Hawaii), cu: 40 [2019-07-11 13:16:43] found  
OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40 [2019-07-11  
13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40  
[2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series  
(Hawaii), cu: 40 [2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9  
390 Series (Hawaii), cu: 40 [2019-07-11 13:16:43] #00, GPU #00 AMD Radeon  
(TM) R9 390 Series (Hawaii), i:960 (8/256), si:2/2, u:8, cu:40 [2019-07-11  
13:16:43] 1.88/3.95/8 GB [2019-07-11 13:16:43] GPU #0 compiling...
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


https://join.skype.com/Lh3vltVf5seJ


.........................................................................................................................................
Join online meeting
.........................................................................................................................................

Fecha: Cada 2 semanas, los domingo, del dom 21 jul al jue 1 ago
Dónde:  
https://github.com/xmrig/xmrig-amd/issues/263?email_source=notifications&email_token=AK5XGQGTGIESAFGR4YEW42LP64NFBA5CNFSM4IBCFEIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G6TPZSA
Calendario:  
reply@reply.github.com
Quién:
     * yairi.medinac@gmail.com - organizador
     * subscribed@noreply.github.com
     * xmrig-amd@noreply.github.com
     * reply@reply.github.com

Detalles del evento:  
https://www.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4cDFqaWMyNDg5MmtjaGExNmNyazhkOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmdwa2NkcTM2ZDBqOGhhMzcxMmthZ3BrNmQxMzJkaGk4OHAzaWhhNDZrc2o4Z3BsNzRzMCByZXBseSthazV4Z3FiZXFva2M1NmxnY2hwM3d0NTNncmt2YmV2Ym5oaGJ4dTM2bXFAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjMjeWFpcmkubWVkaW5hY0BnbWFpbC5jb20wM2YzNzYwMzBmZWExMzA4Yjg3NWNiMGQ0ZmY3ZjFlMmJhZWY0OWE1&ctz=America%2FMexico_City&hl=es_419&es=0

Invitación de Calendario de Google: https://www.google.com/calendar/

Recibes este mensaje de cortesía en la dirección  
reply@reply.github.com de la  
cuenta porque eres uno de los participantes de este evento.

Si deseas dejar de recibir avisos sobre este evento, recházalo. También  
puedes solicitar una cuenta de Google en https://www.google.com/calendar/ y  
controlar la configuración relativa a las notificaciones de todo el  
calendario.

Si reenvías esta invitación, los destinatarios podrían enviar una respuesta  
al organizador y se los podría agregar a la lista de invitados. También  
podrían invitar a otras personas independientemente del estado de su  
invitación o modificar tu confirmación de asistencia. Más información en  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by Yairimedinac4621** [comment]
https://calendar.google.com/calendar/r/week/2019/7/21?eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4cDFqaWMyNDg5MmtjaGExNmNyazhkOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmdwa2NkcTM2ZDBqOGhhMzcxMmthZ3BrNmQxMzJkaGk4OHAzaWhhNDZrc2o4Z3BsNzRzMF8yMDE5MDcyMSB5YWlyaS5tZWRpbmFjQG0&ctz=America/Mexico_City&hl=es_419&es=0&pli=1&sf=true

**Comment by Yairimedinac4621** [comment]
> XMRig AMD v2.14.4
> Windows 10 Enterprise LTSC 2019 x64 (17763.615)
> AMD driver v19.7.1
> 
> Celeron G3900, 5 x Radeon R9 390
> 
> XMRig AMD stops without any error message. Driver problem or something else?
> 
> Log file
> 
> ```
>  * ABOUT        XMRig-AMD/2.14.4 MSVC/2017
>  * LIBS         libuv/1.29.1 OpenCL/2.0 OpenSSL/1.1.1b microhttpd/0.9.63
>  * CPU          Intel(R) Celeron(R) CPU G3900 @ 2.80GHz x64 AES
>  * ALGO         cryptonight, donate=5%
>  * POOL #1      pool.minexmr.com:7777 variant auto
>  * COMMANDS     hashrate, pause, resume
> [2019-07-11 13:16:43] compiling code and initializing GPUs. This will take a while...
> [2019-07-11 13:16:43] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
> [2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
> [2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
> [2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
> [2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
> [2019-07-11 13:16:43] found OpenCL GPU: AMD Radeon (TM) R9 390 Series (Hawaii), cu: 40
> [2019-07-11 13:16:43] #00, GPU #00 AMD Radeon (TM) R9 390 Series (Hawaii), i:960 (8/256), si:2/2, u:8, cu:40
> [2019-07-11 13:16:43]              1.88/3.95/8 GB
> [2019-07-11 13:16:43] GPU #0 compiling...
> ```℅>$* %:'.#._.["Ërror ! Ëvent i"]_#: { _# -*- _/@ #* _ ["https://calendar.google.com/calendar/r/week/2019/7/21?eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4cDFqaWMyNDg5MmtjaGExNmNyazhkOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmdwa2NkcTM2ZDBqOGhhMzcxMmthZ3BrNmQxMzJkaGk4OHAzaWhhNDZrc2o4Z3BsNzRzM}F8yMDE5MDcyMSB5YWlyaS5tZWRpbmFjQG0&ctz=America/Mexico_City&hl=es_419&es=0&pli=1&sf=true "] _/_ _ mm "."_ }':'</‰≠№#>:'. _
#_ fx.i _/#_

**Comment by SlavisaBakic** [comment]
Can you use real keyboard from Internet broser and English language please?

**Comment by Spudz76** [comment]
Driver issue, 19.7.1 is currently broken (too new) - revert to previous should work fine
See also/mostly: https://github.com/fireice-uk/xmr-stak/issues/2473

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
