### ISSUE TITLE
rx/wow on CPU ok, for AMD not supported

### ISSUE THREAD

**Issue by neoncek** [xmrig/xmrig-amd#265]
Hello all, I seems I have an issue with xmrig-amd while mining rx/wow. Similar config is fine on xmrig minig via CPU, but for AMD it gives me error as rx/wow is not known algo.
Win10/64b 13x Rx470 8GB Samsung

**Comment by arS-en** [comment]
same here

**Comment by Spudz76** [comment]
It's not in the release code yet.

You would have to compile from the evo branch and even then it's slow, mainly because it's an anti-GPU algorithm on purpose (designed to run only on CPU, or very wasteful non-profitable on GPUs).  The newest code #270 is way faster and works on Vega or Polaris only, but "way faster" gets the same rates as a relatively slow and small (cheap) `Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz` and is super nasty for the comparative watts used and heat created (and compared to what you'd get on CN-R or others).

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
